---
- name: Log Directories
  file:
    path: "/var/www/{{ item }}/logs"
    owner: vagrant
    group: vagrant
    state: directory
  with_items:
    - gozma12.local
    - adminer.gozma12.local
    - www.gozma12.local

- name: Public Html Directories
  copy:
    src: "public_html/{{ item }}/"
    dest: /var/www/{{ item }}/public_html
    owner: vagrant
    group: vagrant
  with_items:
    - gozma12.local
    - adminer.gozma12.local

- name: Public Html Link
  file:
    src: /vagrant/public_html
    dest: /var/www/www.gozma12.local/public_html
    owner: vagrant
    group: vagrant
    state: link